images:
- name: ghcr.io/lsst-dm/ctrl_ingestd
  newTag: "1.2_test"

namespace: dev-butler

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: dev-butler
  target:
    kind: Namespace
  options:
    allowNameChange: true

replicas:
- name: ingestd
  count: 1

resources:
- ../../common

configMapGenerator:
- name: ingestd-config
  files:
  - ingestd.yml
secretGenerator:
- name: postgres
  files:
  - postgres-user=etc/.secrets/user
  - postgres-password=etc/.secrets/password
